import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Slider } from '@/components/Slider';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const logChange = () => {
    console.log('--logChange');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Slider spike</p>
        <Slider
          numVariants={2}
          onChange={logChange}
        />
      </main>
    </>
  )
}
